export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const START_DOWNLOAD_PRODUCTS = "START_DOWNLOAD_PRODUCTS";
export const DOWNLOAD_PRODUCTS_SUCCESS = "DOWNLOAD_PRODUCTS_SUCCESS";
export const DOWNLOAD_PRODUCTS_ERROR = "START_DOWNLOAD_ERROR";

export const GET_PRODUCT_DELETE = "GET_PRODUCT_DELETE";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_ERROR = "PRODUCT_DELETE_ERROR";
